version: '3.8'
services:
  db:
    image: postgres:13
    container_name: psm_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Use environment variable
      POSTGRES_DB: psm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: psm_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/psm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD} # Use environment variable
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      JWT_SECURITY_SECRET: ${JWT_SECRET} # Use environment variable
    ports:
      - "8080:8080"

volumes:
  postgres_data: