spring:
  application:
    name: ProjectAndDemandManagementSystem
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/psm
    username: postgres
    password: '@MolonPedro0110'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true

jwt:
  security:
    secret: '@MolonPedro0110'

springdoc:
  swagger-ui:
    path: /swagger-ui.html